src/Skyflow.ts
src/container/constants.ts
src/container/external/CollectContainer.ts
src/container/external/RevealContainer.ts
src/container/external/reveal/RevealElement.ts
src/container/internal/index.ts
src/container/internal/reveal/RevealFrame.ts
src/core/reveal.ts
src/libs/element-options.ts
src/utils/validators/index.ts
tests/container/external/reveal/revealElement.test.js
tests/container/external/revealContainer.test.js
tests/container/internal/reveal/revealFrame.test.js
tests/core/reveal.test.js

- Default view of reveal container have replaced text ,provided by customer	
- Add support Custom label and error styling
- Rename id to token in get and reveal methods

Customer request 1a

---

src/Skyflow.ts
src/client/index.ts
src/container/constants.ts
src/container/external/PureJsController.ts
src/container/external/RevealContainer.ts
src/container/internal/pureJs/PureJsFrameController.ts
src/container/internal/reveal/RevealFrameController.ts
src/core/reveal.ts
src/utils/validators/index.ts

Add getById and detokenize methods to handle the new tokenization scheme.

Customer request

---

src/utils/helpers/index.ts
tests/utils/helpers.test.js

SDK-597/Handling BIN Support for AMEX card type

---

README.md

SDK-614/ Add security email in read me file

---

CHANGELOG.md
README.md

SDK-636/ Update read me and changelog

---

samples/UsingScriptTag/skyflowFileUpload.html

SDK-693/ Add sample for file upload

---

README.md

SDK-692/ Add readme for file upload feature

---

src/core-utils/collect.ts
src/core/constants.ts
src/core/external/collect/CollectContainer.ts
src/core/external/collect/CollectElement.ts
src/core/internal/FrameElements.ts
src/core/internal/iFrameForm/index.ts
src/core/internal/index.ts
src/utils/constants.ts
src/utils/helpers/index.ts
src/utils/logs.ts
src/utils/validators/index.ts
tests/core/external/collect/collectContainer.test.js
tests/core/internal/iFrameForm/iFrameForm.test.js
tests/utils/helpers.test.js

SDK-653/ File upload feature in JS SDK

---

src/core/internal/index.ts

SDK-688/ Fix multiple onChange events for setValue()

---

samples/UsingNpm/CustomValidations/src/index.js
samples/UsingScriptTag/CustomValidations.html
src/core/internal/iFrameForm/index.ts

SDK-716/ Update custom validation samples in JS SDK

---

package.json

SDK-699/ Add description in  package.json for js sdk

---

src/core/internal/index.ts

Reverts skyflowapi/skyflow-js#198

Revert "SDK-688/ Fix multiple onChange events for setValue()"

---

CHANGELOG.md

SDK-718/ Update Change log

---

CHANGELOG.md

SDK-744/ Update changelog

---

CHANGELOG.md
src/core-utils/reveal.ts
src/core/internal/reveal/reveal-frame-controller.ts

SDK-777/ Cleanup reveal options in SDK

---

CHANGELOG.md
src/core-utils/reveal.ts
src/core/external/reveal/reveal-container.ts
src/core/external/reveal/reveal-element.ts
src/core/internal/reveal/reveal-frame-controller.ts
src/utils/logs.ts
tests/utils/helpers.test.js

SDK-777/ Remove format regex and replace text options

---

src/utils/validators/index.ts

SDK-762/ Fix conosle errors

---

CHANGELOG.md
README.md

SDK-802/ Add README and Changelog

---

src/core/external/collect/collect-element.ts
src/core/internal/iframe-form/index.ts
src/core/internal/index.ts
src/utils/logs.ts

SDK-794/ Required Fields Internal validation

---

src/core-utils/collect.ts
tests/core-utils/collect.test.js
tests/core/internal/iframe-form/iframe-form.test.js
tests/core/internal/skyflow-frame/skyflow-frame-controller.test.js

SK-43/ Upsert support in JS SDK

---

README.md
src/core-utils/collect.ts
src/core/external/collect/collect-container.ts
src/utils/constants.ts
src/utils/logs.ts
src/utils/validators/index.ts
tests/core-utils/collect.test.js
tests/core/external/collect/collect-container.test.js
tests/utils/validators.test.js

SK-136/ Add upsert option types and fix error handling

---

README.md

SK-168/ Revert Upsert changes in README

---

samples/using-npm/pure-js get/package.json
samples/using-npm/pure-js get/src/index.html
samples/using-npm/pure-js get/src/index.js
samples/using-script-tag/get-pure-js.html

SK-305-add-samples-for-get-method-in-js-sdk

---

README.md

Changes in README
1. Modified example w.r.t event listeners
2. Added example for CARD_NUMBER element in Event listeners section.

SK-404 to correct the example in js sdk readme w.r.t event listener on collect elements

---

README.md
samples/using-npm/pure-js/src/index.js
samples/using-npm/skyflow-elements/src/index.js

Signed-off-by: skyflow-srivyshnavi <srivyshnavi.koduri@skyflow.com>

SK-334 Updated README for column grouping support

---

CHANGELOG.md
README.md
samples/using-npm/composable-elements/package.json
samples/using-npm/composable-elements/src/index.html
samples/using-npm/composable-elements/src/index.js
samples/using-script-tag/composable-elements.html

SK-321/ Add README for Composable Element

---

README.md
samples/using-npm/collect-element-listeners/package.json
samples/using-npm/composable-elements/package.json
samples/using-npm/custom-validations/package.json
samples/using-npm/pure-js get/package.json
samples/using-npm/pure-js/package.json
samples/using-npm/skyflow-elements/package.json

Signed-off-by: skyflow-srivyshnavi <srivyshnavi.koduri@skyflow.com>

SK-433 updated sdk version in samples

---

src/core/internal/iframe-form/index.ts
src/utils/constants.ts
src/utils/helpers/index.ts
src/utils/jwt-utils/index.ts
src/utils/logs.ts
tests/core/internal/iframe-form/iframe-form.test.js
tests/utils/helpers.test.js

- Worked on bug fix for [SK-507](https://skyflow.atlassian.net/browse/SK-507)
- Worked on bug fix for [SK-542](https://skyflow.atlassian.net/browse/SK-542)
- Worked on bug fix for [CUST-889](https://skyflow.atlassian.net/browse/CUST-889)
[SK-507]: https://skyflow.atlassian.net/browse/SK-507?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SK-542]: https://skyflow.atlassian.net/browse/SK-542?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CUST-889]: https://skyflow.atlassian.net/browse/CUST-889?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CUST-889 BUG FIXES

---

samples/using-npm/skyflow-elements-update-records/package.json
samples/using-npm/skyflow-elements-update-records/src/index.html
samples/using-npm/skyflow-elements-update-records/src/index.js
samples/using-script-tag/skyflow-elements-update-records.html

Added samples to include update data through collect element in js sdk.
1. using-npm 
2. using-script-tag

SK-400 create sample to include update data through collect element in js sdk

---

README.md

SK-799 Fix README for JS SDK
- Add `skyflow_id` for `insert`, `collect`, `upsert`, and `composable collect` sample responses

SK-799 Fix README for JS SDK

---

src/client/index.ts
src/core/constants.ts
src/skyflow.ts
src/utils/helpers/index.ts
tests/client.test.js
tests/utils/helpers.test.js

SK-662: Added metrics to JS SDK

---

src/core/external/skyflow-container.ts

Doing release again to check 3DS

FINT-249: release again

---

CHANGELOG.md
README.md
samples/using-npm/pure-js get/package.json
samples/using-npm/pure-js get/src/index.html
samples/using-npm/pure-js get/src/index.js
samples/using-script-tag/get-pure-js.html

- SK-779 Updated README
- SK-779 Updated CHANGELOG
- SK-779 Updated Samples

SK-767 Add options tokens in Get method

---

package.json
src/core/internal/iframe-form/index.ts
src/core/internal/index.ts
src/core/internal/reveal/reveal-frame.ts
src/utils/helpers/index.ts
tests/core/internal/frame-controller.test.js
tests/core/internal/frame-elements.test.js
tests/utils/helpers.test.js
webpack.iframe.js

This reverts commit c69d1adfb58a517e674119c639349dd8db19c9b5.

SK-1242 Revert "SK-1096 SK-1225 replacing of jQuery lib dependency #351

---

src/core/constants.ts
src/core/external/collect/collect-element.ts
src/core/external/common/iframe.ts
src/core/external/reveal/reveal-element.ts
src/core/internal/skyflow-frame/skyflow-frame-controller.ts
src/metrics/index.ts
src/skyflow.ts
src/utils/common/index.ts
src/utils/helpers/index.ts
src/utils/logs.ts
tests/core/external/collect/collect-element.test.js
tests/core/external/common/iframe.test.js
tests/core/external/reveal/reveal-container.test.js
tests/core/external/reveal/reveal-element.test.js
tests/core/internal/skyflow-frame/skyflow-frame-controller.test.js
tests/metrics/metrics.test.js
tests/utils/helpers.test.js

SK-844: iframe latency metrics

---

src/core/external/collect/collect-container.ts
src/core/external/collect/collect-element.ts
src/core/external/collect/compose-collect-container.ts
src/core/external/collect/compose-collect-element.ts
src/core/internal/index.ts
src/libs/element-options.ts
tests/core/external/collect/collect-element.test.js
tests/core/external/collect/composable-element.test.js

- Fix update props dynamically for custom validation `REGEX MATCH RULE` 
- Fix update props dynamically for custom validation `ELEMENT VALUE MATCH RULE`

SK-1583 Fix update method for validations

---

package.json
src/core/external/collect/collect-container.ts
src/core/external/collect/collect-element.ts
src/core/external/collect/compose-collect-container.ts
src/core/external/collect/compose-collect-element.ts
src/core/internal/index.ts
src/libs/element-options.ts
src/skyflow.ts
tests/core/external/collect/collect-element.test.js
tests/core/external/collect/composable-element.test.js

- Fix `update` props dynamically for custom validation `REGEX MATCH RULE`
- Fix `update` props dynamically for custom validation `ELEMENT VALUE MATCH RULE`

SK-1583/Release/24.8.1 patch.1

---

package.json
src/core/constants.ts
src/core/external/collect/collect-container.ts
src/core/external/collect/collect-element.ts
src/core/external/collect/compose-collect-container.ts
src/core/external/reveal/reveal-container.ts
src/core/external/reveal/reveal-element.ts
src/core/external/skyflow-container.ts
src/core/internal/skyflow-frame/skyflow-frame-controller.ts
src/metrics/index.ts
src/skyflow.ts
src/utils/common/index.ts
src/utils/helpers/index.ts
tests/core/external/collect/collect-element.test.js
tests/core/external/reveal/reveal-element.test.js
tests/core/internal/skyflow-frame/skyflow-frame-controller.test.js
tests/metrics/metrics.test.js
tests/utils/helpers.test.js

- Having a RUM solution for tracking iframe events.
- To track iframe performance and loads
- Have done manual testing of the feature under different scenarios like low latency mode

OE-1484: coralogix iframe metrics

---

package.json
src/core/internal/skyflow-frame/skyflow-frame-controller.ts
src/utils/helpers/index.ts
tests/core/internal/skyflow-frame/skyflow-frame-controller.test.js
tests/utils/helpers.test.js

- Having a RUM solution for tracking iframe events.
- To track iframe performance and loads
- Have done manual testing of the feature under different scenarios like low latency mode

OE-1484: react sdk support for coralogix iframe metrics

---

.github/workflows/internal_release.yml

SK-1511: iframe versioning

---

README.md

Reverts skyflowapi/skyflow-js#416

SK-1422 Revert Card branch choice in README file

---

src/core/internal/iframe-form/index.ts
src/utils/helpers/index.ts
tests/core/internal/iframe-form/iframe-form.test.js

Fix Bug in Element value rule validation.

SK-1734: fix element validations for element value match rule

---

.github/workflows/pull_request_template.md
sonar-project.properties

Why 
- Removing sonar login key

SK-1787: fix security issue

---

.github/workflows/common-release.yml

- Fix variable name in common release workflow

SK-1511: fix variable name

---

.github/workflows/common-release.yml

- To fix branch name in release workflow

SK-1511: fix workflow to reslove branch

---

.github/workflows/common-release.yml

SK-1511: fix release workflow

---

samples/using-npm/3ds-helper-functions/package.json
samples/using-npm/3ds-helper-functions/src/index.html
samples/using-npm/3ds-helper-functions/src/index.js
samples/using-script-tag/3ds-helper-functions.html
src/core/external/threeds/threeds.ts
src/skyflow.ts
src/utils/constants.ts
src/utils/logs.ts
tests/core/external/threeds/threeds.test.js
tests/skyflow.test.js

**Description**
- Added helper functions for 3DS

FINT-664:3DS helper functions

---

package.json
samples/using-npm/3ds-helper-functions/package.json
samples/using-npm/3ds-helper-functions/src/index.html
samples/using-npm/3ds-helper-functions/src/index.js
samples/using-script-tag/3ds-helper-functions.html
src/core/external/threeds/threeds.ts
src/skyflow.ts
src/utils/constants.ts
src/utils/logs.ts
tests/core/external/threeds/threeds.test.js

**Description**
- Added helper functions for 3DS

FINT-664: 3DS helper functions

---

.github/workflows/semgrep.yml

This workflow automatically runs Semgrep scans on pull requests to identify security vulnerabilities. All findings are displayed in the build log for review. 
If any issues are detected, a comment is posted directly on the PR.

SC-5130:Update semgrep.yml

---

src/core/external/collect/collect-element.ts
tests/core/external/collect/collect-element.test.js

SK-1925: fix resize observer logic

---

package.json
src/core/external/collect/collect-element.ts
tests/core/external/collect/collect-element.test.js

SK-1925: fix resize observer logic 

---

src/core/internal/index.ts
src/core/internal/reveal/reveal-frame.ts
src/libs/element-options.ts
src/utils/helpers/index.ts
tests/core/internal/frame-controller.test.js

Masking support for collect elements
To make internal release and run existing e2e tests and check nothing is breaking

SK-1562 masking with custom chars

---

package.json
src/core/internal/index.ts
src/core/internal/reveal/reveal-frame.ts
src/libs/element-options.ts
src/utils/constants.ts
src/utils/helpers/index.ts
src/utils/logs.ts
tests/core/internal/frame-controller.test.js
tests/libs/element-options.test.js

- Masking support for collect elements
- To make internal release and run existing e2e tests and check nothing is breaking
- Input should be masked for collect elements when masking is set to true in collect element options
- User should be able to also provide custom masking character

SK-1848 masking support with custom char

---

README.md
samples/using-script-tag/masking.html

- Added masking support in js sdk.
- So, README and sample changes are required to guide users on how to mask element's input.

SK-2000 README and sample for masking

---

package-lock.json
package.json
samples/using-script-tag/3ds-helper-functions.html

This PR updated the dependencies to latest stable versions.
- The versions for dependencies should be updated periodically.
- Up-to-date dependencies in the project.

SK-1927 Update dependencies to latest stable versions

---

src/skyflow.ts

Internal release for adding method signature for different type of container in container function in js sdk
Strong, autocompletion and type hints based on type
Improved autocompletion and clarity in IDEs, and it is more maintainable and scalable. It follows TypeScript.

SK-2023 Internal release for adding method signature for container function in js sdk

---

package.json
src/skyflow.ts

Public release for adding method signature for different type of container in container function in js sdk
Strong, auto completion and type hints based on type
Improved auto completion and clarity in IDEs, and it is more maintainable and scalable. It follows TypeScript.

SK-2037 Public release for adding method signature for container function 

---

CHANGELOG.md

Update CHANGELOG with all release information.
- We maintain a CHANGELOG with all the information for releases.
- Well maintained and up-to-date CHANGELOG with information for all releases.

SK-2037 Update CHANGELOG

---

src/core/external/threeds/threeds.ts

**Description**
- Added new field in browser details 3DS helper function
- This new field is to support EMV Co. new version i.e. 2.3.1

FINT-790:Update 3DS browserDetails helper function

---

src/core/external/collect/collect-container.ts

Why:
The SDK currently checks for the iframe in the window object, but it fails to access the iframe when our iframe is embedded inside another iframe.
Goal:
Update the SDK to reliably access the iframe from the window, even when it is nested within another iframe.

SK-2080 fix window error

---

src/core/external/collect/collect-container.ts
tests/core/external/collect/collect-container.test.js

The SDK currently checks for the iframe in the window object, but it fails to access the iframe when our iframe is embedded inside another iframe.
Update the SDK to reliably access the iframe from the window, even when it is nested within another iframe.

SK-2129: refactor stale elements code

---

CHANGELOG.md
samples/using-typescript/3ds-helper-functions/package.json
samples/using-typescript/collect-element-listeners/package.json
samples/using-typescript/composable-elements-update/package.json
samples/using-typescript/composable-elements-update/src/index.ts
samples/using-typescript/composable-elements/package.json
samples/using-typescript/custom-validations/package.json
samples/using-typescript/file-render/package.json
samples/using-typescript/pure-js-delete/package.json
samples/using-typescript/pure-js-get/package.json
samples/using-typescript/pure-js/package.json
samples/using-typescript/skyflow-elements-input-formatting/package.json
samples/using-typescript/skyflow-elements-update-records/package.json
samples/using-typescript/skyflow-elements-update/package.json
samples/using-typescript/skyflow-elements/package.json

This PR updates version of `skyflow-js` dependency in typescript samples. And also updates CHANGELOG with release information.

SK-2101 Update CHANGELOG

---

samples/using-script-tag/collect-elements.html

- Currently there is no sample without event listeners
- Event listeners should not be part of sample

SK-2162 update collect elements sample

---

src/client/index.ts
src/core-utils/delete.ts
src/core-utils/reveal.ts
src/core/external/collect/collect-container.ts
src/core/external/collect/collect-element.ts
src/core/external/collect/compose-collect-container.ts
src/core/external/collect/compose-collect-element.ts
src/core/external/common/iframe.ts
src/core/external/reveal/reveal-container.ts
src/core/external/reveal/reveal-element.ts
src/core/internal/internal-types/index.ts
src/core/internal/skyflow-frame/skyflow-frame-controller.ts
src/libs/jss-styles.ts
src/libs/styles.ts
src/skyflow.ts
src/utils/bus-events/index.ts
src/utils/common/index.ts
src/utils/helpers/index.ts
src/utils/validators/index.ts
tests/core/external/collect/collect-container.test.js
tests/core/external/collect/collect-container.test.ts
tests/core/external/collect/collect-element.test.ts
tests/core/external/collect/composable-container.test.js
tests/core/external/collect/composable-container.test.ts
tests/core/external/collect/composable-element.test.ts
tests/core/external/reveal/reveal-container.test.ts
tests/core/external/reveal/reveal-element.test.ts

This PR fixes the typescipt gaps in internal SDK code for reveal and composable element flows.
- The SDK code had typescript related gaps where types were not properly defined for method parameters, return types, variables, etc.
- We identified and fixed those gaps by introducing proper types for better typescript support and type safety.
- Tested the changes manually.
- Fixed some failing existing unit tests.
- Added unit tests in typescript with type safety.

SK-2144 Fix typescript gaps in internal code

---

package-lock.json
package.json

**Why**
- Few critical vulnerabilities have been identified in the in js sdk. These vulnerabilities need to be addressed to ensure the security and stability of the codebase.
**Outcome**
- Resolve the identified vulnerabilities to improve the security and stability of the JS SDK.

SK-2166: Fix critical vulnerabilities

---

package.json
src/core-utils/reveal.ts
src/core/external/collect/collect-element.ts
src/core/external/common/iframe.ts
src/core/external/reveal/composable-reveal-container.ts
src/core/external/reveal/composable-reveal-internal.ts
src/core/internal/iframe-form/index.ts
src/core/internal/index.ts
src/core/internal/reveal/reveal-frame.ts
src/utils/common/index.ts
tests/utils/jwt-utils.test.js

**Why**
- Fix keyboard actions according to WCAG guidelines.
- Add file meta data in the file render response
**Outcome**
- Improved accessibility by aligning keyboard actions with WCAG guidelines.
- Enhanced file render response by including fileMetadata.

SK-2239: Add file metadata in file render and fix keyboard actions according to WCAG guidelines
